version: '3.8'

services:
  machtiani:
    mem_limit: 0.5g
    build:
      context: .
      dockerfile: Dockerfile
    container_name: machtiani
    ports:
      - "5071:5071"
    volumes:
      - ./:/app
      - ./data:/data
    extra_hosts:
      # allow the container to resolve host.docker.internal → host gateway
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      # point your app’s MLX client at the host’s MLX-LM server
      - MLX_SERVER_URL=http://host.docker.internal:8080
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5071", "--reload"]
    depends_on:
      - commit-file-retrieval

  commit-file-retrieval:
    mem_limit: 0.75g
    build:
      context: ./machtiani-commit-file-retrieval
      dockerfile: Dockerfile
    container_name: commit-file-retrieval
    ports:
      - "5070:5070"
    volumes:
      - ./machtiani-commit-file-retrieval:/app
      - commit_file_retrieval:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - MLX_SERVER_URL=http://host.docker.internal:8080
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5070", "--reload"]

volumes:
  commit_file_retrieval:

