version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway 
    container_name: api-gateway
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - api-gateway/.env
    volumes:
      - caddy_data:/data  # Mount a Docker volume for persisting certificate data
    command: ["sh", "-c", "caddy fmt --overwrite /etc/caddy/Caddyfile && caddy run --config /etc/caddy/Caddyfile --adapter caddyfile"]

volumes:
  caddy_data:
