version: '3.8'

services:
  machtiani:
    mem_limit: 2g
    build:
      context: .
      dockerfile: Dockerfile
    container_name: machtiani
    ports:
      - "5071:5071"
    volumes:
      - ./:/app
      - ./data:/data
    # Allows to work with a local llm on local host, etc.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=CRITICAL
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5071", "--reload"]
    depends_on:
      - commit-file-retrieval

  commit-file-retrieval:
    mem_limit: 2g
    build:
      context: ./machtiani-commit-file-retrieval
      dockerfile: Dockerfile
    container_name: commit-file-retrieval
    ports:
      - "5070:5070"
    volumes:
      - ./machtiani-commit-file-retrieval:/app
      - commit_file_retrieval:/data
    # Allows to work with a local llm on local host, etc.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=CRITICAL
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5070", "--reload"]

volumes:
  commit_file_retrieval:

