version: '3.8'

services:
  machtiani:
    build: .
    container_name: machtiani
    ports:
      - "5071:5071"
    volumes:
      - ./data:/data
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5071", "--workers", "4"]
    depends_on:
      - commit-file-retrieval

  commit-file-retrieval:
    build:
      context: ./machtiani-commit-file-retrieval
    env_file:
      - machtiani-commit-file-retrieval/.env
    container_name: commit-file-retrieval
    ports:
      - "5070:5070"
    volumes:
      - commit_file_retrieval:/data
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5070", "--timeout-keep-alive", "1200", "--workers", "4"]

volumes:
  commit_file_retrieval:

