version: '3.8'

services:
  machtiani:
    build: .
    container_name: machtiani
    ports:
      - "5071:5071"
    volumes:
      - ./data:/data
    command: ["poetry", "run", "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "5071"]
    depends_on:
      - commit-file-retrieval

  commit-file-retrieval:
    build:
      context: ./machtiani-commit-file-retrieval
    env_file:
      - machtiani-commit-file-retrieval/.env
    container_name: commit-file-retrieval
    ports:
      - "5070:5070"
    volumes:
      - ./machtiani-commit-file-retrieval/data:/data
    command: ["poetry", "run", "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "5070"]

  authenticator:
    build:
      context: .  # Assuming the Dockerfile is in the same directory
    container_name: authenticator
    ports:
      - "80:80"
    environment:
      - AUTH0_CLIENT_ID={your_auth0_client_id}        # Replace with your Auth0 Client ID
      - AUTH0_CLIENT_SECRET={your_auth0_client_secret} # Replace with your Auth0 Client Secret
      - AUTH0_DOMAIN={your_auth0_domain}               # Replace with your Auth0 Domain
      - TOKEN_SECRET=your_secret_key                   # Replace with a random secret key
      - REMOTE_IP=<remote-ip>                          # Replace with your remote IP
